[email]
smtp_server = "smtp.gmail.com"
smtp_port = 587
sender_email = "alberto.bortolotti@acus.eu"
sender_password = "funq xyza sifo zesg"  # App Password (da configurare in gmail)
recipient_email = "alberto.bortolotti@acus.eu"     # Dove vuoi ricevere i risultati
